### ISSUE TITLE
在和PTGI一起加载时，门的阴影渲染错误

### ISSUE THREAD

**Issue by xitieshiz2** [GeForceLegend/Minecraft-Default-3D#11]
![image](https://s3.ax1x.com/2021/02/21/yIvuBd.png)
RT
本人配置：
Windows 10 2009 x64
i7-10700
RTX 2060
Java 8u281 x64
Minecraft 1.16.5
Optifine G6
SEUS PTGI E12（还有材质作者您自己修改的SEUS PTGI HRR TEST GFME也出现了这个bug

**Comment by GeForceLegend** [comment]
PTGI内各种方块的遮光体积是硬编码在着色器文件内的，不会随资源包内模型的变化而改变。此bug不属于资源包问题，并且无法通过资源包修复。
