### ISSUE TITLE
该材质与林业的兼容有问题

### ISSUE THREAD

**Issue by EmptyDreams** [GeForceLegend/Minecraft-Default-3D#12]
我使用的材质版本为：`1.12_Optifine.v1.3.3`
我使用的林业版本为：`1.12.2-5.8.2.422`
加载该材质后，林业的所有蜜蜂的材质变的透明，只有描边线条还有颜色

**Comment by GeForceLegend** [comment]
由于蜜蜂的物品模型使用了builtin/generated并且拥有大于两个贴图造成的，由于我这个资源包设计之初没考虑过mod兼容，你安装的版本要修复的话挺麻烦的，争取在下一个版本提供快速修复的方式（但是这个bug因为一些原因依旧会默认存在）
