### ISSUE TITLE
1.18.1版本药水瓶物品模型出错

### ISSUE THREAD

**Issue by habaneraa** [GeForceLegend/Minecraft-Default-3D#15]
作者您好，我在新的1.18.1版本使用资源包模型发现了个别模型出现了小错误

包括：

- 药水瓶模型models/item/potion.json
- 喷溅药水瓶模型models/item/splash_potion.json
![屏幕截图 2021-12-23 120332](https://user-images.githubusercontent.com/95517280/147186328-23a1281a-04f8-46ce-95b8-beedd29a5532.png)

资源包非常精致！给你点赞！

**Comment by GeForceLegend** [comment]
本资源包不仅包括模型，还包括了一些纹理。你使用的其他资源包覆盖了本资源包内的药水瓶模型纹理，导致纹理与模型不适配。不属于本资源包的原因。
