### ISSUE TITLE
与其它资源包混搭时出现模型错误的情况

### ISSUE THREAD

**Issue by LiHua2** [GeForceLegend/Minecraft-Default-3D#16]
Stay True1.16(下)和3D default1.16.2 v1.4.2(上)混搭时出现模型与贴图不匹配的情况，矿石和铁门的表现尤为明显。研究了一下似乎是这个资源包对于部分使用原版贴图的方块模型没有提供贴图导致在混搭时系统使用下方资源包的贴图与这个资源包的模型结合，出现错位的情况。建议为所有模型增加贴图，以提高和其他资源包混搭时的兼容性。

**Comment by GeForceLegend** [comment]
原版纹理属于MOJANG AB创作的内容，应该仅拿来参考而不是放在第三方资源包的目录里。如果您真的想多个包一起加载，可以把有问题的纹理对应的原版纹理手动加入资源包（或者自己制作一个用来覆盖其他纹理的资源包）
