### ISSUE TITLE
玻璃的显示有点问题

### ISSUE THREAD

**Issue by NOVACarambola** [GeForceLegend/Minecraft-Default-3D#18]
原版：
![2022-04-12_09 09 47](https://user-images.githubusercontent.com/103470936/162859192-bddf6ee9-7f44-4ab4-a8ac-df221536223d.png)
材质包
![2022-04-12_09 09 59](https://user-images.githubusercontent.com/103470936/162859224-96521d8f-43e3-4e9e-811d-1413512a566a.png)
：

**Comment by GeForceLegend** [comment]
刻意为之

**Comment by NOVACarambola** [comment]
这样不会很挡视野吗
