### ISSUE TITLE
关于书架的凹槽是梯形的

### ISSUE THREAD

**Issue by NOVACarambola** [GeForceLegend/Minecraft-Default-3D#19]
书架凹槽怎么是梯形的，旁边的书像是嵌进去的，这个是BUG吗
![2022-04-23_11 12 48](https://user-images.githubusercontent.com/103470936/164873508-d7bc7101-ac6d-40d4-9db5-0e7f4033927d.png)
![Inked2022-04-23_11 12 48](https://user-images.githubusercontent.com/103470936/164873631-45cc724e-f4fc-4c00-a8e8-9dc0bf4b8ea1.jpg)

**Comment by NOVACarambola** [comment]
![Uploading Inked2022-04-23_11.12.48.jpg…]()

**Comment by GeForceLegend** [comment]
考虑各种因素之后刻意为之
