### ISSUE TITLE
玻璃瓶和龙息在叠加了其它材质包的时候显示出现了问题

### ISSUE THREAD

**Issue by NOVACarambola** [GeForceLegend/Minecraft-Default-3D#20]
其他药水显示正常，但玻璃瓶和龙息显示错误（已将其他材质包覆盖在3D材质上方）
![2022-04-30_23 11 16](https://user-images.githubusercontent.com/103470936/166111349-ba9a7db0-3772-4b66-bbf2-0737f49140a6.png)

**Comment by GeForceLegend** [comment]
不对与其他资源包的兼容性负责，觉得有问题自己删除模型
