### ISSUE TITLE
crash with  AbyssalCraft

### ISSUE THREAD

**Issue by MiracleBelief** [GeForceLegend/Minecraft-Default-3D#23]
游戏版本：1.12.2
材质包版本：1.4.2
深渊国度版本：1.12.2-1.10.4
日志链接https://gist.github.com/MiracleBelief/333f690a9e0fccbba8643dd6043510bf
问题描述：当我接触到任何深渊国度中的卷轴（Scroll）类物品时，游戏发生崩溃。包括并不限于：创造模式鼠标移到创造背包内该物品上方，该物品出现在世界中........
很喜欢您的材质包，如您没有再维护1.12版本的打算，希望您能于此回复一下。辛苦您了。

**Comment by GeForceLegend** [comment]
尝试删除assets/minecraft/models/items/generated.json

**Comment by MiracleBelief** [comment]
没有问题了，谢谢您
