### ISSUE TITLE
[建议]与Xekr的红石显示材质包兼容

### ISSUE THREAD

**Issue by andywowws** [GeForceLegend/Minecraft-Default-3D#24]
当同时使用本材质包和Xekr红石显示材质包时,为下界合金镐或钻石镐附上时运后,镐子不会按照Xekr材质包显示出两个镐头,调整材质包顺序无用

**Comment by GeForceLegend** [comment]
尝试删除assets/minecraft/models/item/generated.json

**Comment by GeForceLegend** [comment]
如果长时间不回复，我将视此issue为已解决
