### ISSUE TITLE
手持某些食物会出现网格

### ISSUE THREAD

**Issue by Aknirex** [GeForceLegend/Minecraft-Default-3D#25]
手持一些食物会出现网格，如附件图所示，目前发现熟肉、腐肉、生熟鱼、烤土豆等会出现此类情况。网格会随物品一起运动

![2023-02-03_15 04 11](https://user-images.githubusercontent.com/124341146/216536977-7ba7fd1a-b747-4671-aaa1-7202d57507e8.png)
![2023-02-03_15 05 42](https://user-images.githubusercontent.com/124341146/216537012-c5c39807-b05d-4985-8446-5e8390e2bc28.png)
![2023-02-03_15 18 54](https://user-images.githubusercontent.com/124341146/216537029-03532c76-458a-4670-bbcc-8f224f4f4e02.png)

**Comment by GeForceLegend** [comment]
issue template是真不看一眼啊哥
