### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by DominoKorean** [GeForceLegend/Minecraft-Default-3D#26]
![image](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/110039366/bfb5c823-76d8-44f0-b672-f49f4757e908)
"gorday color"

**Comment by GeForceLegend** [comment]
This is an issue of https://github.com/GeForceLegend/SEUS_PTGI_GFME, but not https://github.com/GeForceLegend/Minecraft-3D-Default. I get it anyway.
