### ISSUE TITLE
Oculus on 1.18.2 with this RP, both Vanilla and Texture RP - tree saplings have ugly outlines with Complementary Reimagined shader

### ISSUE THREAD

**Issue by xFirefalconx** [GeForceLegend/Minecraft-Default-3D#27]
1. Make sure this bug is caused by the resource pack it self, but not mods or other resource packs. I will not work on compatibility with these resources.

Tested by changing different parameters and reloading/restacking resources. As soon as your resource pack is active, the "ugly outlines" appear. I also checked the resource pack's textures, opened them up close and searched for pixel fragments, they are fine, no borders that would trigger such a behaviour. They also don't show those lines when looked at separately, with the shader active. I am also using Complementary Reimagined, which might also have to do with the issue. 
**New info! This also happens in vanilla, without a resource pack that changes shape or texture of those tree saplings!**

3. A latest.log (in `.minecraft/logs`), crash report (in `.minecraft/crash-reports`) or even hs_err_pid(logID).log (in `.minecraft`) if exists and its create time matches crashing will helps a lot. Provide them if you can.

There are not any error messages related to the issue. What I can decipher from the appearance of the problem is the way the vertices, faces, meshes, whatever objects are rendered in a way that is not entirely invisible, causing these fragments, the shader tries to add shadow/lighting to these even though they are alpha 0%. 
Important: Tools from the same resource pack are fine! So far I only noticed saplings to be broken. The tools (tested with wooden tools) have a 3D pattern so I assume that the saplings are bypassed/ignored, but not entirely. I'd prefer the saplings to be 2D instead of 3D when holding them in my hand when there's no other way to fix this. I also dug within the 3D default resource pack to find any related files for the saplings but there exist none. I would have checked them for inconsistencies compared to the wooden tools that I analyzed, or the sort. 
See the resource pack names: 
I edited the other pack slightly, but that got nothing to do with the saplings. 
If you zoom in and look closely, you can see fragments in white/dark colors. As if there was a bleeding edge, failed canceling of light edges or the like. I will also reach out to the shader devs but I believe this got to do with the way the 3D effect is achieved. Can you confirm my suspicion? Do you render each pixel in 3D or the sort, even if it's empty?

![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/2537145d-bbeb-4357-8f26-62838a0cde32)
![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/6849e16b-6884-4d45-a566-b2a68a6780a5)
![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/74606a5a-e82a-44dd-a65d-9f1b170d981f)
![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/d412c08f-e87c-4d2b-87e9-30f06ea17be4)

proof screenshots for Vanilla:
![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/fb2a4dce-ca81-41b1-a45d-7bf62c47e2c9)
![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/7b53c887-481e-49f0-b885-158ab8594f1c)

Counter proof time! I disable the resource pack "3D-Default" - 
**And this is what the texture pack I have looks like when I disable 3D-default resource pack:**
![grafik](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/106652912/695e9b4f-a7fe-46e6-82d7-5216050012ee)
So there is a >90% chance that the resource pack 3D-default got an issue, OR an incompatibility with saplings in Complementary Reimagined, running on Oculus.

**Comment by GeForceLegend** [comment]
There are some tears on vanilla item model, and I'v made a model inteded to fix it in a hacky way. I dont know if sodium/oculus breaks my fix, you can try this rp alone with Optifine or no mod installed. If you want to use this rp with oculus or sodium, you can delete assets/minecraft/models/item/generated.json

**Comment by xFirefalconx** [comment]
Thanks for the fast reply, I moved the concerned file one folder up in case it is needed anytime later. The fragments are now gone 🎉
