### ISSUE TITLE
Potions

### ISSUE THREAD

**Issue by ChrissW-R1** [GeForceLegend/Minecraft-Default-3D#29]
1. Make sure this bug is caused by the resource pack it self, but not mods or other resource packs. I will not work on compatibility with these resources.
Tested with Vanilla client. Fresh installation of 1.20.1 only added the texture pack.

2. If you are experiencing any bug related to items, including crash while rendering something, try deleteing `assets/minecraft/models/item/generated.json`. Its my hacky way to fix [MC-73186](https://bugs.mojang.com/browse/MC-73186).
No crash

3. A latest.log (in `.minecraft/logs`), crash report (in `.minecraft/crash-reports`) or even hs_err_pid(logID).log (in `.minecraft`) if exists and its create time matches crashing will helps a lot. Provide them if you can.
No crash

All normal potions are not shown right (see screenshots). Splash and lingering potions works fine.
![2023-12-06_22 20 00](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/1086210/f64490dc-b3bc-48da-8b5b-365222a2458a)
![2023-12-06_22 20 24](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/1086210/57930eb9-6710-4cf8-9fd5-0d3ab7ff18e3)

**Comment by GeForceLegend** [comment]
This resourcepack modded some vanilla textures used by models. If you load this resourcepack with other resourcepacks, this has a great chance to happen, and I cannot provide help about this, since I don't know how other resourcepack creators treat with their models and textures.
