### ISSUE TITLE
关于箱子的问题

### ISSUE THREAD

**Issue by bilibilijandy** [GeForceLegend/Minecraft-Default-3D#30]
在mc1.17.1版本中，箱子的钥匙扣的地方的渲染出现了问题
![image](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/141329748/f8e2a587-6d92-4679-8bb3-c59917d47548)
![image](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/141329748/acdb535a-115c-40ec-9963-691d4361b9c7)
![image](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/141329748/ab428b98-96c1-4cd3-b38a-d05455f081ec)

**Comment by GeForceLegend** [comment]
请使用匹配的版本而非盲目使用适配最新Minecraft的版本。1.19.3的时候MOJANG修改了原版的箱子实体模型，导致资源包内的Optifine自定义实体模型需要修改以匹配新版本，自然老版本的效果就会炸
