### ISSUE TITLE
3D Default Overrides All Other Resource Packs

### ISSUE THREAD

**Issue by Norb3** [GeForceLegend/Minecraft-Default-3D#32]
3d Default seems to override all other resource packs regardless of where it's placed in the pack list in MC settings. This is only prevented by disabling the pack by moving it out of the active pack list.

I noticed this with redstone wire. I have the VanillaTweaks option for clean wire and it's always at the top of my active packs yet 3D vanilla wiring from 3D Default overrides it until I disable the pack. It also "covers over" the power values from the VanillaTweaks option for that, so the numbers are underneath the 3D wiring.

I'm trying to use the pack in 1.20.4 and want to use it there and in 1.20.6+.

Thanks!

P.S. Please consider using the ResPackOpts mod to allow customization for 3D Default. Thanx.

**Comment by Norb3** [comment]
Never mind. Must have been a memory problem because the effect went away after rebooting my computer & restarting the game. Weird, as memory problems always are.

**Comment by Norb3** [comment]
I take that back. The behavior is still there. The only way the pack _doesn't_ override every other loaded pack is if I move it to the bottom of the list, below even the MC default. This means, of course, the the default overrides 3D Default. The behavior ends up exactly the same as if I take 3D off the list entirely, so all my other packs do correctly override those below them.

**Comment by GeForceLegend** [comment]
I'm not sure about what does your resourcepack or mods do, but 3D Default doesn't modified blockstate file of redstone wires, it just modified models. If only models change can override all other resourcepack, then all other resourepacks with models will do it too.
Vanilla resourcepack is working as this:
- reading hardcoded blockstates file fo find used models
- reading models to find used textures

So it's very common that model changes can override texture changes, even their pack is overrided by another pack only contains texture.

And, no plan for any mod support currently.
