### ISSUE TITLE
3D 经验瓶

### ISSUE THREAD

**Issue by freeze-dolphin** [GeForceLegend/Minecraft-Default-3D#33]
建议为经验瓶使用和药水瓶类似的3D模型

![image](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/40729044/340ff99e-d6e2-4bcf-a558-3cd82a0b9542)

**Comment by GeForceLegend** [comment]
附魔之瓶的发光效果感觉不是很好做，而且这玩意在原版也不是和药水一个栏位的
（以及，当前我主要精力不在这个项目上，所以一般情况下只会做一做新版本的东西）

**Comment by freeze-dolphin** [comment]
粗略画了一下这个材质，见 [Minecraft-3D-Default-Exp-Bottle-Fork ](https://github.com/freeze-dolphin/Minecraft-3D-Default-Exp-Bottle-Fork)

**Comment by GeForceLegend** [comment]
内部液体颜色不太对，没有凸显整体发光的特点，不能让人第一眼就看出来是附魔之瓶

如果让我来设计的话，会考虑在外层用一圈负模型做发光，同时设计一个独立的瓶塞（就像附魔之瓶本身纹理那样）

不过我已经不太想继续去更新老版本的东西了，如果你的模型你自己喜欢的话可以自用，我暂时没有做这个东西的计划，附魔之瓶本身在原版里面的出现频率和作用也不算怎么大

**Comment by MysteryPSD** [comment]
> 内部液体颜色不太对，没有凸显整体发光的特点，不能让人第一眼就看出来是附魔之瓶
> 
> 如果让我来设计的话，会考虑在外层用一圈负模型做发光，同时设计一个独立的瓶塞（就像附魔之瓶本身纹理那样）
> 
> 不过我已经不太想继续去更新老版本的东西了，如果你的模型你自己喜欢的话可以自用，我暂时没有做这个东西的计划，附魔之瓶本身在原版里面的出现频率和作用也不算怎么大

我实际应用下来发现负模型的光照全是反的，大部分情况下我不是非常喜欢这种效果（但是我在部分内挖孔上还是用了
