### ISSUE TITLE
Skeleton head and ribs are misplace and doubled

### ISSUE THREAD

**Issue by hxOutL** [GeForceLegend/Minecraft-Default-3D#34]
The current version of 3D Default 1.10.1, Minecraft 1.20.4 released on Jun 14, 2024, has an issue with skeletons, heads, and ribs. The image shows the skeleton's head and rib are doubled and misplaced at the left side of the mobs. I've looked closely at my games my resource pack and mods, and the resources pack itself shows a bug on Skeleton.
![2024-06-27_20 30 45](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/174019559/2e07192f-4256-4235-ab91-9d5bcb4c0865)

**Comment by GeForceLegend** [comment]
Cannot see this in Optifine 1.20.6 I9 Pre1. If you are using alternatives, try Optifine first.
![2024-06-28_09 49 06](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/41003546/2894c954-9e00-4dff-a6c4-3e4bc536c19d)

**Comment by hxOutL** [comment]
okay, problem solved. Thanks!

**Comment by GeForceLegend** [comment]
Then you can report a issue to the CEM feature provider you are using
