### ISSUE TITLE
incompatibility with fresh animations

### ISSUE THREAD

**Issue by carbage14** [GeForceLegend/Minecraft-Default-3D#36]
since the mod renders skeletons as 3d, it appears as off to the side on the "fresh animations" version of the skeleton. one solution i can think of is uploading a duplicate modpack that has all 3d models excluding mobs.

![image](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/172576427/8d2a42ab-bce4-4ae7-b7c1-a0a121b75267)

**Comment by GeForceLegend** [comment]
Looks like same as #34 . Maybe an issue related to CEM provider mod you are using (at least Optifine works fine according to that issue)

**Comment by carbage14** [comment]
ill look into it, but i think it's the way that "fresh animations" completely overhauls the animations of nearly all mobs produces this problem, because if i disable it, the skeleton looks normal.

**Comment by GeForceLegend** [comment]
Fixed, coming in next version. Not sure if there is still other incompatibilities, please continue reporting if you find some.

**Comment by carbage14** [comment]
okie dokie, thanks
