### ISSUE TITLE
问题和建议

### ISSUE THREAD

**Issue by Anan1a** [GeForceLegend/Minecraft-Default-3D#37]
与Continuity内置的Glass Pane Culling Fix材质包一同使用玻璃板会变得奇怪 
![屏幕截图 2024-07-09 113412](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/116565083/8d2c18c1-510e-4ce5-a3d0-67f4c1430cf8)

我修改了竹甘蔗，希望你喜欢
![屏幕截图 2024-07-09 113830](https://github.com/GeForceLegend/Minecraft-3D-Default/assets/116565083/27ef88a6-4ee5-45cc-810d-faf7e7902624)
文件：
[sugar_cane.json](https://github.com/user-attachments/files/16137630/sugar_cane.json)

**Comment by Anan1a** [comment]
如果模型可以被使用上，那就太好了
╰(*°▽°*)╯

**Comment by GeForceLegend** [comment]
1. 我的一切开发环境都是以Optifine为准，所以Optifine没问题的话我这边是几乎不会考虑处理的
2. 甘蔗存在多根叠一起的情况，你这个模型显然没有考虑到这种情况

**Comment by Anan1a** [comment]
@GeForceLegend 
我有考虑过，我的修改的甘蔗有一节被埋在地下，如果堆叠的话，正好是可以连接上的
<img width="420" alt="屏幕截图 2024-07-09 194054-1" src="https://github.com/GeForceLegend/Minecraft-3D-Default/assets/116565083/8da2165a-87fb-4bcd-afaf-1d1a36317b86">
