### ISSUE TITLE
Trapdoors when flat against a block culls backside, showing void world.

### ISSUE THREAD

**Issue by handsome-steve** [GeForceLegend/Minecraft-Default-3D#39]
This is more a flaw in the  pack, but the trapdoors when flat against a surface cull the back facing block into the world, almost like noclip view perspective.

![2024-09-19_18 40 28](https://github.com/user-attachments/assets/94af9e7c-2042-4583-8a3c-f32d87df9a49)
![2024-09-19_18 40 59](https://github.com/user-attachments/assets/276f346a-1534-4eed-be55-e6e6a99c1955)
![2024-09-19_18 40 41](https://github.com/user-attachments/assets/10316e3b-c1e2-488c-b656-d4d44a769c6b)
![2024-09-19_18 40 44](https://github.com/user-attachments/assets/804b1b57-2025-4fa5-81a1-a768046490a1)

**Comment by tmeedend** [comment]
Hi, 
I have the same problem. I am on minecraft 1.21.1 and last version of this mod. I can even see the caves below with this glitch.

But apart from that, good job!
