### ISSUE TITLE
1.15.2箱子没有3d效果

### ISSUE THREAD

**Issue by ZTL-UwU** [GeForceLegend/Minecraft-Default-3D#4]
箱子是原版箱子的材质，在1.14里就有3d材质

**Comment by GeForceLegend** [comment]
@zhangtianli2006 箱子的模型需要Optifine支持，目前1.15的Optifine测试版暂时不支持箱子的自定义实体模型，需要等待Optifine更新。而且1.15箱子本身的贴图排版也有变化，1.15的箱子的模型得重新制做。

**Comment by ZTL-UwU** [comment]
期待
