### ISSUE TITLE
Potential Bug Report

### ISSUE THREAD

**Issue by MastroGiwrghs** [GeForceLegend/Minecraft-Default-3D#40]
I have a problem, the texture pack has a bug that deforms the potions when brewing and i was wondering is it some bug from the pack it self or other texture packs are the cause of it? It's for version 1.10.2 of the texture pack
 (1.21 Minecraft)

![2024-11-23_20 33 29](https://github.com/user-attachments/assets/0ca96c4f-c1c7-4306-99b5-4c56d9772f7e)
![2024-11-23_20 33 58](https://github.com/user-attachments/assets/940b81ce-64d1-4f97-8a7d-82dc3247f099)

**Comment by GeForceLegend** [comment]
Resource packs with models are highly not recommended using with other packs
