### ISSUE TITLE
X-Ray cobwebs

### ISSUE THREAD

**Issue by Coding-Kiwi** [GeForceLegend/Minecraft-Default-3D#41]
Spider webs / Cobwebs are full blocks I guess? this causes X-ray when using a shader

![2024-11-30_19 47 20](https://github.com/user-attachments/assets/b22cf8b0-19c9-4c1e-a92c-5044dfa96c7e)

**Comment by GeForceLegend** [comment]
Check your mods. This is not possible happening in vanilla with only shader loader.

**Comment by mirai-toto** [comment]
I had the same issue when using `More Culling` mod, disabling `BlockState Culling` which disable aggressive culling solved the issue.
