### ISSUE TITLE
winsdom光影下床和箱子BUG

### ISSUE THREAD

**Issue by ZTL-UwU** [GeForceLegend/Minecraft-Default-3D#5]
版本1.15， optifine pre12
光影: winsdom3232
床和箱子变成全黑的方块

**Comment by GeForceLegend** [comment]
使用原版材质也是这样，涉及范围包括所有方块类实体和部分其他的实体，估计是Optifine预览版或者Wisdom对于实体处理的问题 @zhangtianli2006
