### ISSUE TITLE
20w20b使用 20w19a材质 篝火贴图部分错误

### ISSUE THREAD

**Issue by Philogag** [GeForceLegend/Minecraft-Default-3D#6]
游戏版本 20w20b纯净
资源包 Release 1.2.0 - 3D.Default.1.16_Snapshot_20w19a.zip
![image](https://user-images.githubusercontent.com/44018455/82746695-403bcb00-9dc5-11ea-9ae7-0ed7d3da3ace.png)
![image](https://user-images.githubusercontent.com/44018455/82746735-b5a79b80-9dc5-11ea-84ae-f7d2f6473280.png)

**Comment by GeForceLegend** [comment]
Fixed in Release 1.2.1
