### ISSUE TITLE
材质在1.16.3版本上不是太兼容

### ISSUE THREAD

**Issue by Gu-f** [GeForceLegend/Minecraft-Default-3D#8]
1.16.3上的好多都无法3D化，只有个别的如工作台、铁轨等可以3D化。希望作者能做一下兼容

**Comment by GeForceLegend** [comment]
首先，请确认其他版本是否出现此问题。这个资源包并没有做全方块3D，只对一部分方块做了3D处理。
其次，1.16.3理论上与1.16.2+的包兼容。

**Comment by GeForceLegend** [comment]
No enough imformation（没有足够信息）
